// expectedObjects.js  
window.expectedTealiumLinkObjects = [
{
  "eventAction": "OnClick",
  "eventCategory": "HeaderLink",
  "eventLabel": "TopMenu_Logo",
  "destinationUrl": "https://staging.eurostar.com/uk-en",
  "eventName": /^NavigationEvent_v(\d{1})$/,
  "event": "TealiumLink"
},
{
	eventAction: "OnClick",
	destinationUrl: /^(.*)$/,
	eventCategory: "HeaderLink",
	eventLabel: "TopMenu_Account",
	eventName: /^NavigationEvent_v(\d{1})$/,
	event: "TealiumLink"
},
  {
    "eventAction": "OnClick",
    "eventCategory": "HeaderLink",
    "eventLabel": "TopMenu_MarketSelectorModal_Open",
    "eventName": /^NavigationEvent_v(\d{1})$/,
    "event": "TealiumLink"
  },
  {
    "eventAction": "OnClick",
    "eventCategory": "HeaderLink",
    "eventLabel": "TopMenu_MarketSelectorModal_Select",
    "destinationUrl": "https://staging.eurostar.com/uk-en",
    "eventName": /^NavigationEvent_v(\d{1})$/,
    "event": "TealiumLink"
  },
{
	eventAction: "OnClick",
	eventCategory: "HeaderLink",
	eventLabel: "TopMenu_EurostarApp",
	destinationUrl: "https://staging.eurostar.comtravel-info/your-trip/eurostar-app",
	eventName: /^NavigationEvent_v(\d{1})$/,
	event: "TealiumLink"
},	
{
  "eventCategory": "Internal Promotion",
  "eventAction": "Impression",
  "eventNonInteraction": "true",
  "eventLabel": /\s.*\s/,
  "promotion_id": [/\s.*\s/],
  "promotion_name": [/\s.*\s/],
  "promotion_creative": [/\s.*\s/],
  "promotion_position": [/\d{2}_\d{2}$/],
  "page_element_cta": /^.+$/,
  "eventName": "ImpressionEvent",
  "event": "TealiumLink"
},	
{
	"eventAction": "Click",
	"eventCategory": "Internal Promotion",
	"promotion_name": /\s.*\s/,
	"promotion_position": /\d{2}_\d{2}$/,
	"page_element_cta": /^.+$/,
	"eventLabel": "Disruption",
	"promotion_id": ["Disruption"],
	"promotion_creative": /^.+$/,
	"eventName": "InteractionEvent",
	"event": "TealiumLink"
},
{
  "eventAction": "Expand",
  "eventCategory": "Booking Magnet",
  "eventLabel": /^(P|H|T)(:Expand)$/,
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Collapse",
  "eventCategory": "Booking Magnet",
  "eventLabel": /^(P|H|T)(:Collapse)$/,
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},	
{
  "eventAction": "Field Start",
  "eventLabel": /^(T|P|H):From$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Field Start",
  "eventLabel":/^(T|P|H):To$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},	
{
  "eventAction": "Field Completion",
  "eventLabel": /^(T:From_\d{7}|P:From_\d{3}|H:From_\d{3})$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Field Completion",
  "eventLabel": /^(T:To_\d{7}|P:To_\d{3}|H:To_\d{3})$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Click",
  "eventLabel": /^(T|P|H):Search$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Field Completion",
  "eventLabel": /^(T|P|H):Calendar|Outbound$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink",
  "product": /^(trains|packages|hotels)$/
},
{
  "eventAction": "Field Start",
  "eventLabel": /^(T|P|H):Calendar|Inbound$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Field Completion",
  "eventLabel": /^(T|P|H):Calendar|Inbound$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Field Start",
  "eventLabel": /^(T|P|H):Passenger$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Field Completion",
  "eventLabel": /^(T|P|H):Passenger$/,
  "eventCategory": "Booking Magnet",
  "interactionSection": "header",
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
  {
	eventAction: "Click",
	eventLabel: /^(T|P|H):Select Outbound Month$/,
	eventCategory: "Booking Magnet",
	interactionSection: "header",
	formName: "bm-no-pricing",
	eventName: "InteractionEvent",
	event: "TealiumLink",
},	
{
  "eventAction": "Select Outbound",
  "eventCategory": "Train Selection",
  "eventLabel": /^(Eurostar Standard|Eurostar Plus|Eurostar Premier)(\|.*)?$/,
  "noChanges": /^(0|null|undefined)$/,
  "sClassOutbound": /^(Eurostar Standard|Eurostar Plus|Eurostar Premier)$/,
  "sOutboundTime": /^(\d{2}:\d{2}|undefined|null)$/, 
  "sOutboundArrivalTime": /^(\d{2}:\d{2}|undefined|null)$/, 
  "sOutboundConnectionCode": /^(null|undefined)$/,
  "sOutboundConnectionOperator": /^(null|undefined)$/,
  "sTrainNumberOutbound": /^(\d{4}|null|undefined)$/,
  "sTrainTarriffOutbound": /^([A-Z0-9]{11}|null|undefined)$/,
  "basket_value": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "sTrainSaleTagsOutbound": /^(null|undefined|[A-Z0-9]+)$/,
  "basket_value_inpoints": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "priceAdultOutbound": /^(0|[1-9][0-9]{0,3}|10000)(\.[0-9]{1,2})?$/,
  "priceChildOutbound": /^(0|[1-9][0-9]{0,3}|10000)(\.[0-9]{1,2})?$/,
  "priceYouthOutbound": /^(0|[1-9][0-9]{0,3}|10000)(\.[0-9]{1,2})?$/,
  "priceSeniorOutbound": /^(0|[1-9][0-9]{0,3}|10000)(\.[0-9]{1,2})?$/,
  "sTrainTypeOutbound": /^ESTAR_PUB_(STD|PLUS|PREM)$/,
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Select Inbound",
  "eventCategory": "Train Selection",
  "eventLabel": /^(Eurostar Standard|Eurostar Plus|Eurostar Premier)$/,
  "noChanges": /^(0|null|undefined)$/,
  "sClassInbound": /^(Eurostar Standard|Eurostar Plus|Eurostar Premier)$/,
  "sInboundTime": /^\d{2}:\d{2}$/,
  "sInboundArrivalTime": /^\d{2}:\d{2}$/,
  "sInboundConnectionCode": /^(null|undefined)$/,
  "sInboundConnectionOperator": /^(null|undefined)$/,
  "sTrainNumberInbound": /^(\d{4}|null|undefined)$/,
  "sTrainTarriffInbound": /^([A-Z0-9]{11}|null|undefined)$/,
  "basket_value": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "sTrainSaleTagsInbound": /^(.*)$/,
  "basket_value_inpoints": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "priceAdultInbound": /^(0|[1-9][0-9]{0,3}|10000)(\.[0-9]{1,2})?$/,
  "priceChildInbound": /^(0|[1-9][0-9]{0,3}|10000)(\.[0-9]{1,2})?$/,
  "priceYouthInbound": /^(0|[1-9][0-9]{0,3}|10000)(\.[0-9]{1,2})?$/,
  "priceSeniorInbound": /^(0|[1-9][0-9]{0,3}|10000)(\.[0-9]{1,2})?$/,
  "sTrainTypeInbound": /^ESTAR_PUB_(STD|PLUS|PREM)$/,
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Select ",
  "eventCategory": "Train Selection",
  "eventLabel": /^(Eurostar Standard|Eurostar Plus|Eurostar Premier)$/,
  "noChanges": /^(0|null|undefined)$/,
  "sClassInbound": /^(Eurostar Standard|Eurostar Plus|Eurostar Premier)$/,
  "sInboundTime": /^\d{2}:\d{2}$/,
  "sInboundArrivalTime": /^\d{2}:\d{2}$/,
  "sInboundConnectionCode": null,
  "sInboundConnectionOperator": null,
  "sTrainNumberInbound": /^\d{4}$/,
  "sTrainTarriffInbound": /^[A-Z0-9]{11}$/,
  "basket_value": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "sTrainSaleTagsInbound": /^(.*)$/,
  "basket_value_inpoints": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "priceAdultInbound": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "priceChildInbound": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "priceYouthInbound": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "priceSeniorInbound": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "sTrainTypeInbound": /^ESTAR_PUB_(STD|PLUS|PREM)$/,
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Open Outbound Fare Details",
  "eventCategory": "Train Selection",
  "eventLabel": /^Eurostar (Standard|Plus|Premier)$/,
  "noChanges": /^(0|null|undefined)$/,
  "sClassOutbound": /^Eurostar (Standard|Plus|Premier)$/,
  "sOutboundTime": /^\d{2}:\d{2}$/,
  "sOutboundArrivalTime": /^\d{2}:\d{2}$/,
  "sOutboundConnectionCode": /^(null|undefined)$/,
  "sOutboundConnectionOperator": /^(null|undefined)$/,
  "sTrainNumberOutbound": /^\d{4}$/,
  "sTrainTarriffOutbound": /^[A-Z0-9]{11}$/,
  "basket_value": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "sTrainSaleTagsOutbound": /^.*$/,
  "basket_value_inpoints": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "priceAdultOutbound": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "priceChildOutbound": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "priceYouthOutbound": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "priceSeniorOutbound": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
}, 
{
  "eventAction": "Open Inbound Fare Details",
  "eventCategory": "Train Selection",
  "eventLabel": /^Eurostar (Standard|Plus|Premier)$/,
  "noChanges": /^(0|null|undefined)$/,
  "sClassInbound": /^(Eurostar Standard|Eurostar Plus|Eurostar Premier)$/,
  "sInboundTime": /^\d{2}:\d{2}$/,
  "sInboundArrivalTime": /^\d{2}:\d{2}$/,
  "sInboundConnectionCode": null,
  "sInboundConnectionOperator": null,
  "sTrainNumberInbound": /^\d{4}$/,
  "sTrainTarriffInbound": /^[A-Z0-9]{11}$/,
  "basket_value": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "sTrainSaleTagsInbound": /^.*$/,
  "basket_value_inpoints": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "priceAdultInbound": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "priceChildInbound": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "priceYouthInbound": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "priceSeniorInbound": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},

{
  "eventAction": "Outbound",
  "eventCategory": "Date Picker",
  "eventLabel": /^(\+|\-)\d{1,20}\:(Next|Previous)$/,
  "sDateOutbound": /^\d{4}-\d{2}-\d{2}$/,
  "basket_value": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "basket_value_inpoints": /^(0|[1-9][0-9]{0,3}|10000)$/,
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  "eventAction": "Hotel Selection",
  "eventCategory": "Product tile",
  "hHotelDetails": /^.+\|\d+\|.+$/,
  "hotelId": [/^\d+$/],
  "hotelName": [/^.+$/],
  "hHotelPackagePromotion": [/^\d+$/],
  "hHotelPackageSavings": [/^\d+$/],
  "hHotelPriceAllPassengers": [/^\d+$/],
  "hHotelReviewCount": [/^\d+$/],
  "hHotelReviewScore": [/^\d+(\.\d+)?$/],
  "hHotelStarRating": [/^\d+$/],
  "eventName": "InteractionEvent",
  "event": "TealiumLink"
},
{
  eventAction: "Room selection",
  eventCategory: "Hotel room card",
  eventLabel: "Continue",
  currency: /^(GBP|EUR|USD)$/,
  ecommerce_action: "add",
  basket_value: /^\d+(\.\d{2})?$/,
  basket_value_inpoints: /^\d+$/,
  products_count: /^\d+$/,
  product_id: [/^\d+$/],
  product_name: [/^.+$/],
  product_quantity: [1],
  product_price: [/^\d+(\.\d{2})?$/],
  product_category: ["hotels"],
  product_variant: [/^.+$/],
  product_hotel_room_extra: [/^.+$/],
  product_cancellation_policy: [/^full|none$/],
  eventName: "InteractionEvent",
  event: "TealiumLink"
},
{
	eventCategory: "Hotel Upsell",
	eventAction: "Viewed",
	eventLabel: "Impression",
	eventNonInteraction: true,
	package_searchresults: /^(.*)$/,
	ecommerce_action: "product impressions",
	products_count: 5,
	product_id: [/^\d+$/],
        product_name: [/^.+$/],
	product_quantity: [1],
        product_price: [/^\d+(\.\d{2})?$/],
	product_price_inpoints:  [/^\d+(\.\d{2})?$/],
	product_brand: [/^(.*)$/],
	product_category: [/^(hotels)$/],
	product_departure_date: [/^\d{4}-\d{2}-\d{2}$/],
	product_return_date: [/^\d{4}-\d{2}-\d{2}$/],
	product_hotel_origin_code: [/^\d+$/],
	product_hotel_destination_code: [/^\d+$/],
	product_hotel_occupancy: [/^\d\|\d\|\d\|\d\|\d$/],
	product_hotel_starrating: [/^\d$/],
	product_hotel_review_count: [/^\d+$/],
	product_hotel_review_score: [/^(.*)$/],
	product_hotel_promotion: [/^(.*)$/],
	product_hotel_package_savings: [/^(.*)$/],
	eventName: "ImpressionEvent",
	event: "TealiumLink"
},	
{
eventCategory: "Insurance Selection",
eventAction: /^(Uns|S)elected Policy$/,
eventLabel: /^(Comprehensive|Cancellation) insurance$/,
insuranceProviders: "Allianz",
insuranceType: /^(Comprehensive|Cancellation) insurance$/,
insurancePrice: /^\d+(\.\d{2})?$/,
basket_value: /^\d+(\.\d{2})?$/,
eventName: "InteractionEvent",
event: "TealiumLink"
},
{
  "event": "TealiumLink",
  "eventName": "InteractionEvent", 
  "eventCategory": "Side Basket",
  "eventAction": /^(Expand|Collapse)$/
},
{
eventAction: "Edit",
eventLabel: /^(Out|In)bound Train$/,
eventCategory: "Side Basket",
eventName: "InteractionEvent",
event: "TealiumLink"
},	
{
eventAction: "Login",
currency: /^[A-Z]{3}$/,
funnel_name: /^Login|CustomerDashboard|Trains|Hotels|Packages|Subscriptions|ManageBooking|BusinessDashboard|Snap$/,
page_name: "Login",
page_category: "Checkout",
ld_version: "design-system",
eventCategory: "Login or Register",
eventLabel: /^.{1,20}$/,
formName: /^checkout$/,
eventName: "InteractionEvent",
event: "TealiumLink"
},
{
  event: "TealiumLink",
  eventName: "InteractionEvent",
  eventCategory: "Passenger Details",
  eventAction: "Select A Passenger",
  eventLabel: "Existing Passenger"
},
{
  event: "TealiumLink",
  eventName: "InteractionEvent",
  eventCategory: "Passenger Details",
  eventAction: "Select A Passenger",
  eventLabel: "New Passenger"
},
{
	event: "TealiumLink",
	eventName: "InteractionEvent",
	eventCategory: "Passenger Details",
	eventAction: "Click",
	eventLabel: "Save New Passenger To Account:Check"
},
{
	event: "TealiumLink",
	eventName: "InteractionEvent",
	eventCategory: "Passenger Details",
	eventAction: "Click",
	eventLabel: "Save New Passenger To Account:Uncheck"
},
{
	eventAction: "Page Load",
	currency: /^(GBP|EUR|USD)$/,
	funnel_name: /^Login|CustomerDashboard|Trains|Hotels|Packages|Subscriptions|ManageBooking|BusinessDashboard|Snap$/,
	page_name: "Checkout",
	page_category: "Checkout",
	ld_version: "design-system",
	eventCategory: "Page Timing",
	eventLabel: "Page Timing",
	eventNonInteraction: true,
	timings_cls: /^(.*)$/,
	timings_inp: /^(.*)$/,
	timings_lcp: /^(.*)$/,
	eventName: "SystemEvent",
	event: "TealiumLink"
},
  {
  event: "TealiumLink",
  eventName: "InteractionEvent",
  eventCategory: "Seating interaction",
  eventAction: /^"Seating changes (saved|discarded)"$/,
  eventLabel: /^"(inbound|outbound) (Changes made|No Changes made)"$/,
  ecommerce_action: "seat map",
  pnr: /^[a-zA-Z0-9]{6}$/,
  product_id: ["7015400 - 8727100"],
  product_brand: ["ES"],
  product_category: ["trains"],
  product_variant: /^\["(inbound|outbound)"\]$/,
  product_departure_date: /^\["\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])"\]$/,
  product_return_date: /^\["\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])"\]$/,
  product_train_class: ["Standard"],
  product_train_route: ["london route"],
  product_train_origin_stationcode: ["8727100"],
  product_train_destination_stationcode: ["7015400"],
  product_train_number: ["9009"],
  product_train_fbccode: ["H19RSXARBG"],
  product_train_departuretime: ["07:43"],
  product_train_arrivaltime: ["11:02"],
  product_train_tickettype: ["PUB_STD_SF"],
  product_train_passenger_type: ["adult"],
  product_train_fare_name: ["through fare"],
  product_train_fare_type: ["ES_SR"]
},
        {"eventCategory":"Seating interaction","eventAction":"Seating changes saved","eventLabel":"outbound No Changes","ecommerce_action":"seat map","products_count":4,"product_status":["upcoming","upcoming"],"product_name":["8776500 - 8768600:adult","8727100 - 8400058:adult"],"product_id":["8776500 - 8768600","8727100 - 8400058"],"product_quantity":[2,2],"product_price":["182.60","230.00"],"product_brand":["SN","ER"],"product_category":["trains","trains"],"product_variant":["outbound","outbound"],"product_departure_date":["2025-03-28","2025-03-28"],"product_return_date":[],"product_train_class":["Standard Première","Eurostar Plus"],"product_train_route":["continent route","continent route"],"product_train_origin_stationcode":["8776500","8727100"],"product_train_destination_stationcode":["8768600","8400058"],"product_train_number":["6194","9339"],"product_train_fbccode":["SNCF1SFAD","TH01PSXASBEN"],"product_train_departuretime":["07:02","12:22"],"product_train_arrivaltime":["10:48","15:50"],"product_train_numberofconnections":[2,2],"product_train_connectioncode":["8776500","8727100"],"product_train_connectionoperator":["SNCF","Eurostar"],"product_train_tickettype":["SNCF1SF","RED_ESTAR_PUB_PLUS"],"product_train_passenger_type":["adult","adult"],"product_hotel_destination_code":[],"product_hotel_starrating":[],"product_hotel_origin_code":[],"product_hotel_occupancy":[],"product_hotel_review_count":[],"product_hotel_review_score":[],"product_hotel_room_extra":[],"product_hotel_promotion":[],"product_hotel_package_savings":[],"product_train_fare_name":["summated fare","summated fare"],"product_train_fare_type":["ER_SN","ER_SN"],"eventName":"InteractionEvent","event":"TealiumLink"},


{
	"eventCategory":"Train Upgrade",
	"eventAction":"Selected Outbound",
	"eventLabel":"Eurostar Standard > Eurostar Plus",
	"ecommerce_action":"add",
	"basket_value":/^\d+$/,
	"basket_value_inpoints":/^\d+$/,
	"pointsOrRegular":/^(regular booking|points booking)$/,
	"products_count":/^\d+$/,
	"product_name":[/^\d{7} - \d{7}(:adult)?$/], 
	"product_id":[/^\d{7} - \d{7}$/],
	"product_quantity":[/^\d+$/],
	"product_price":[/^\d+\.\d{2}$/],
	"product_price_inpoints":[/^\d+$/],
	"product_brand":[/^[A-Z]{2}$/],
	"product_category":["trains"],
	"product_variant":["/inbound|outbound/"],
	"product_departure_date":[/^\d{4}-\d{2}-\d{2}$/],
	"product_return_date":[null],
	"product_train_class": [/^Eurostar (Standard|Plus|Premier)$/],
        "product_train_route": [/^(london route|continent route)$/],
	"product_train_origin_stationcode": [/^\d{7}$/],
        "product_train_destination_stationcode": [/^\d{7}$/],
        "product_train_number": [/^\d{4}$/],
	"product_train_fbccode": [/^.*$/], // some may be null
        "product_train_departuretime": [/^\d{2}:\d{2}$/],
        "product_train_arrivaltime": [/^\d{2}:\d{2}$/],
	"product_train_numberofconnections": [/^\d+$/],
	"product_train_connectioncode":[],
	"product_train_connectionoperator": [/^(null|Eurostar|SNCF)?$/],
        "product_train_tickettype": [/^(ESTAR_PUB_(STD|PLUS|PREM)|SNCF1SF|RED_ESTAR_PUB_PLUS|null)$/],
	"product_train_passenger_type": ["adult"],
	"product_train_fare_name":[],
	"product_train_fare_type":[],
	"eventName":"InteractionEvent",
	"event":"TealiumLink"
},
{
	eventCategory: "Train Upgrade",
	eventAction: "Unselected Outbound",
	eventLabel: "Eurostar Standard > Eurostar Plus",
	upgradeRoute: "outbound",
	upgradeClass: /^(Eurostar Standard|Eurostar Plus|Eurostar Premier)$/,
	upgradePrice: /^\d+(\.\d{2})?$/,
	sTrainNumberOutbound: /^ES:(\d{4})$/,
	sOutboundTime: /^\d{2}:\d{2}$/,
	sClassOutbound: /^(Eurostar Standard|Eurostar Plus|Eurostar Premier)$/,
	"sTrainTarriffOutbound": /^[A-Z0-9]{11}$/,
	basket_value: /^\d+(\.\d{1,2})?$/,
	eventName: "InteractionEvent",
	event: "TealiumLink" 
},
{
	"eventAction":"Login",
	"currency":/^(GBP|EUR|USD)$/,
	funnel_name: /^Login|CustomerDashboard|Trains|Hotels|Packages|Subscriptions|ManageBooking|BusinessDashboard|Snap$/,
	"page_name":"Login",
	"page_category":"Checkout",
	"ld_version":"design-system",
	"eventCategory":"Login or Register",
	"eventLabel":"Check out as a guest",
	"formName":"checkout",
	"eventName":"InteractionEvent",
	"event":"TealiumLink"
},
        {"event":"TealiumView","page_category":"Bookings","isLoggedIn":"true","customer_hashedemail":"52296546df7b53c4242e0ecae775f6bf3c3aa919387cd39c0979fe1a9d5b8b3a","customer_is_admin":"false","loyaltyTier":"Etoile","membershipID":"30838110000069353","membershipDetails":"Points: 1363811; Points to upgrade: N/A","pointsToSpend":1363811,"pointsToUpgrade":null,"subscriptionType":"premium-pass","subscriptionDuration":6,"subscriptionRemainingDuration":134,"mktOptions":"false","page_name":"Bookings/UpcomingBookings"},
        {"eventAction":"Click","eventCategory":"Bookings","eventLabel":"View Booking","eventName":"InteractionEvent","event":"TealiumLink"},
        {
            eventAction: "Click",
            currency: /^(GBP|EUR|USD)$/,
            funnel_name: /^Login|CustomerDashboard|Trains|Hotels|Packages|Subscriptions|ManageBooking|BusinessDashboard|Snap$/,
            page_name: "Checkout",
            page_category: "Checkout",
            ld_version: "design-system",
            eventCategory: "Checkout Interaction",
            eventLabel: "Buy Now",
            eventName: "InteractionEvent",
            event: "TealiumLink"
        },
        {
            eventAction: "Form Submission",
            currency: /^(GBP|EUR|USD)$/,
            funnel_name: /^(Login|CustomerDashboard|Trains|Hotels|Packages|Subscriptions|ManageBooking|BusinessDashboard|Snap)$/,
            page_name: "Checkout",
            page_category: "Checkout",
            ld_version: "design-system",
            eventCategory: "Checkout Interaction",
            paymentDetails: /^(SavedCard|Card|ApplePay|GooglePay|iDEAL|PayPal|Sofort|Invoice|Card\|Loyalty_Points|Card\|Voucher|Billie|Klarna_BNPL)$/,
            paymentCardType: /^(mc|visa|amex|cartebancaire|jcb|diners|discover)$/,
            eventName: "InteractionEvent",
            event: "TealiumLink"
        },
        {
            eventAction: "Select A Passenger",
            currency: /^(GBP|EUR|USD)$/,
            funnel_name: /^Login|CustomerDashboard|Trains|Hotels|Packages|Subscriptions|ManageBooking|BusinessDashboard|Snap$/,
            page_name: "Checkout",
            page_category: "Checkout",
            ld_version: "design-system",
            eventCategory: "Booking Contact",
            eventLabel: "Existing Passenger",
            eventName: "InteractionEvent",
            event: "TealiumLink"
        },
        {
            eventAction: "Points payment unselected",
            currency: /^(GBP|EUR|USD)$/,
            funnel_name: /^Login|CustomerDashboard|Trains|Hotels|Packages|Subscriptions|ManageBooking|BusinessDashboard|Snap$/,
            page_name: "Checkout",
            page_category: "Checkout",
            ld_version: "design-system",
            eventCategory: "Points usage",
            eventName: "InteractionEvent",
            event: "TealiumLink"
        },
        {
            event: "TealiumLink",
            eventName: "InteractionEvent",
            eventCategory: "Checkout Interaction",
            eventAction: "Payment Method Selection",
            paymentDetails: /^(Saved)?Card$/
        },
        {"eventAction":/^Field (Start|Complete)$/,"currency":/^(GBP|EUR|USD)$/,"funnel_name":"Trains","page_name":"Checkout","page_category":"Checkout","ld_version":"design-system","eventCategory":"Passenger Details","eventLabel":"passengers.0.firstName","eventName":"InteractionEvent","event":"TealiumLink"},
        {"eventAction":/^Field (Start|Complete)$/,"currency":/^(GBP|EUR|USD)$/,"funnel_name":"Trains","page_name":"Checkout","page_category":"Checkout","ld_version":"design-system","eventCategory":"Passenger Details","eventLabel":"passengers.0.lastName","eventName":"InteractionEvent","event":"TealiumLink"},
        {"eventAction":/^Field (Start|Complete)$/,"currency":/^(GBP|EUR|USD)$/,"funnel_name":"Trains","page_name":"Checkout","page_category":"Checkout","ld_version":"design-system","eventCategory":"Passenger Details","eventLabel":"passengers.0.email","eventName":"InteractionEvent","event":"TealiumLink"},
        {"eventAction":/^Field (Start|Complete)$/,"currency":/^(GBP|EUR|USD)$/,"funnel_name":"Trains","page_name":"Checkout","page_category":"Checkout","ld_version":"design-system","eventCategory":"Passenger Details","eventLabel":"passengers.0.mobile","eventName":"InteractionEvent","event":"TealiumLink"},
        {
		"eventAction":"Click",
		"currency":/^(GBP|EUR|USD)$/,
		"funnel_name":/^(Trains|Hotels|Packages)$/,
		"page_name":"Checkout",
		"page_category":"Checkout",
		"ld_version":"design-system",
		"eventCategory":"Newsletter",
		"eventLabel":"Opt-Out",
		"mktOptions":"false",
		"eventName":"InteractionEvent",
		"event":"TealiumLink"
	},
        {"eventCategory":"Passenger detail","eventAction":"Contact details","eventLabel":"Save contact details:button","eventName":"InteractionEvent","event":"TealiumLink"},
        {
            eventAction: "Validation Error",
            currency: /^(GBP|EUR|USD)$/,
            funnel_name: /^Login|CustomerDashboard|Trains|Hotels|Packages|Subscriptions|ManageBooking|BusinessDashboard|Snap$/,
            page_name: "Checkout",
            page_category: "Checkout",
            ld_version: "design-system",
            eventCategory: "Error",
            eventLabel: /^.*$/,
            errorMessage: /^.*$/,
            eventName: "ErrorEvent",
            event: "TealiumLink"
        },
	{
		eventAction: "Expand",
		currency: /^(GBP|EUR|USD)$/,
		funnel_name: /^Login|CustomerDashboard|Trains|Hotels|Packages|Subscriptions|ManageBooking|BusinessDashboard|Snap$/,
		page_name: "Checkout",
		page_category: "Checkout",
		ld_version: "design-system",
		eventCategory: "Passenger Details",
		eventLabel: "Membership number accordion",
		eventName: "InteractionEvent",
		event: "TealiumLink"
	},
        {
            event: 'TealiumLink',
            eventName: 'InteractionEvent',
            eventCategory: 'Optional question',
            eventAction: 'Reason for travel - Selection',
            eventLabel: ["reasons for this travel : business", "reasons for this travel : holiday", "reasons for this travel : visiting family or friends"]
        },
        {"currency":/^(GBP|EUR|USD)$/,"funnel_name":"Trains","page_category":"Checkout","ld_version":"design-system","event":"TealiumView","activityType":"train exchange","isLoggedIn":false,"customer_hashedemail":null,"customer_is_admin":null,"businessID":null,"loyaltyTier":null,"membershipID":null,"membershipDetails":null,"pointsToSpend":null,"pointsToUpgrade":null,"directOrConnection":"direct","sJourneyType":"One way","sFromCode":"7015400","sFromName":"London St Pancras Int'l","sToCode":"8727100","sToName":"Paris Gare du Nord","sDateOutbound":"2024-10-23","sDateInbound":"","sTravelHorizon":0,"sTravelDuration":null,"sPaxTotal":1,"sPaxAdult":1,"sPaxChildren":0,"sPaxInfants":0,"sPaxSenior":0,"sPaxYouth":0,"sPaxCompanion":0,"basket_value_inpoints":0,"pointsOrRegular":"regular booking","promoBooking":"","ecommerce_action":"checkout","payment_methods":"Card|GooglePay|Invoice|PayPal","club_eurostar_discount":"none","basket_value":270,"products_count":1,"product_brand":["ES"],"product_id":["7015400 - 8727100"],"product_category":["trains"],"product_name":["7015400 - 8727100:adult"],"product_price":["270.00"],"product_price_inpoints":["0"],"product_quantity":[1],"product_train_numberofconnections":[1],"product_departure_date":["2024-10-23"],"product_train_departuretime":["18:01"],"product_train_fbccode":["H01PSXASBGX"],"product_train_number":["9046"],"product_variant":["outbound"],"product_hotel_origin_code":[],"product_hotel_destination_code":[],"product_hotel_occupancy":[],"product_hotel_starrating":[],"product_hotel_review_count":[],"product_hotel_review_score":[],"product_hotel_room_extra":[],"product_return_date":[],"product_train_class":["Standard Premier"],"product_train_route":["london route"],"product_train_origin_stationcode":["7015400"],"product_train_destination_stationcode":["8727100"],"product_train_arrivaltime":["21:28"],"product_train_tickettype":["ES_PUB_SP"],"product_train_connectionoperator":[null],"product_train_passenger_type":["adult"],"product_train_fare_name":[],"product_train_fare_type":[],"page_name":"Checkout"},
	{
		eventAction: "Points payment selected",
		currency: /^(GBP|EUR|USD)$/,
		funnel_name: /^Login|CustomerDashboard|Trains|Hotels|Packages|Subscriptions|ManageBooking|BusinessDashboard|Snap$/,
		page_name: "Checkout",
		page_category: "Checkout",
		ld_version: "design-system",
		eventCategory: "Points usage",
		eventLabel: /^.{1,3}$/,
		eventName: "InteractionEvent",
		event: "TealiumLink"
	},
        {
            event: "TealiumLink",
            eventName: "InteractionEvent",
            eventCategory: "Booking Contact",
            eventAction: "Select A Passenger",
            eventLabel: "Existing Passenger"
        },
        {
            "event":"TealiumView",
            "page_category":"Overview",
            "isLoggedIn":"true",
            "customer_hashedemail":/^.{1,64}$/,
            "customer_is_admin":"false",
            "loyaltyTier":"Carte Blanche",
            "membershipID":/^.{1,17}$/,
            "membershipDetails":"Points: 801; Points to upgrade: 2859",
            "pointsToSpend":801,
            "pointsToUpgrade":2859,
            "subscriptionType":"frequent-pass",
            "subscriptionDuration":6,
            "subscriptionRemainingDuration":107,
            "mktOptions":"false",
            "page_name":"Overview"
        },
            {
        currency: /^(GBP|EUR|USD)$/,
        funnel_name: /^Login|CustomerDashboard|Trains|Hotels|Packages|Subscriptions|ManageBooking|BusinessDashboard|Snap$/,
        page_category: "Checkout",
        ld_version: "design-system",
        event: "TealiumView",
        activityType: "train exchange",
        isLoggedIn: /(true|false)/,
        customer_hashedemail: /^.{0,64}$/,
        customer_is_admin: /(true|false|null)/,
        businessID: null,
        loyaltyTier: /^(Carte Blanche|Silver|Gold|null)$/,
        membershipID: /^.{0,17}$/,
        membershipDetails: /^.{0,100}$/,
        pointsToSpend: /\d*/,
        pointsToUpgrade: /\d*/,
        directOrConnection: /(direct|connection)/,
        sJourneyType: /(One way|Return)/,
        sFromCode: /^\d{7}$/,
        sFromName: /.+/,
        sToCode: /^\d{7}$/,
        sToName: /.+/,
        sDateOutbound: /^\d{4}-\d{2}-\d{2}$/,
        sDateInbound: /^$|^\d{4}-\d{2}-\d{2}$/,
        sTravelHorizon: /\d+/,
        sTravelDuration: null,
        sPaxTotal: /\d+/,
        sPaxAdult: /\d+/,
        sPaxChildren: /\d+/,
        sPaxInfants: /\d+/,
        sPaxSenior: /\d+/,
        sPaxYouth: /\d+/,
        sPaxCompanion: /(\d+)?/,
        basket_value_inpoints: /\d+/,
        pointsOrRegular: /(regular booking|points booking)/,
        promoBooking: /^.*$/,
        ecommerce_action: "checkout",
        payment_methods: /Card|GooglePay|PayPal/,
        club_eurostar_discount: /(none|member)/,
        basket_value: /^\d+(\.\d{1,2})?$/,
        products_count: /\d+/,
        product_brand: [/^(ES|[A-Z]+)$/],
        product_id: [/^\d{7} - \d{7}$/],
        product_category: ["trains"],
        product_name: [/^\d{7} - \d{7}:adult$/],
        product_price: [/^\d+(\.\d{2})?$/],
        product_price_inpoints: [/^\d+$/],
        product_quantity: [/\d+/],
        product_train_numberofconnections: [/\d+/],
        product_departure_date: [/^\d{4}-\d{2}-\d{2}$/],
        product_train_departuretime: [/^\d{2}:\d{2}$/],
        product_train_fbccode: [/^.+$/],
        product_train_number: [/^\d+$/],
        product_variant: ["outbound"],
        product_hotel_origin_code: [],
        product_hotel_destination_code: [],
        product_hotel_occupancy: [],
        product_hotel_starrating: [],
        product_hotel_review_count: [],
        product_hotel_review_score: [],
        product_hotel_room_extra: [],
        product_return_date: [],
        product_train_class: ["Eurostar Plus"],
        product_train_route: ["london route"],
        product_train_origin_stationcode: [/^\d{7}$/],
        product_train_destination_stationcode: [/^\d{7}$/],
        product_train_arrivaltime: [/^\d{2}:\d{2}$/],
        product_train_tickettype: ["ESTAR_PUB_PLUS"],
        product_train_connectionoperator: [null],
        product_train_passenger_type: ["adult"],
        product_train_fare_name: [],
        product_train_fare_type: [],
        page_name: "Checkout"
    },
{
	eventAction: "Register",
	currency: /^(GBP|EUR|USD)$/,
	funnel_name: /^(Trains|Packages|Hotels)$/,
	page_name: "BookingConfirmation",
	page_category: "BookingConfirmation",
	eventCategory: "Sign Up Now",
	eventLabel: "Register click",
	formName: "checkout",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
	{
	eventAction: "Validation Error",
	currency: /^(GBP|EUR|USD)$/,
	funnel_name: /^(Trains|Packages|Hotels)$/,
	page_name: "BookingConfirmation",
	page_category: "BookingConfirmation",
	eventCategory: "Error",
	eventLabel: /^(.*)$/,
	errorMessage: /^(.*)$/,
	formName: "checkout",
	eventName: "ErrorEvent",
	event: "TealiumLink"
},
{
	eventAction: "Verification",
	currency: /^(GBP|EUR|USD)$/,
	funnel_name: /^(Trains|Packages|Hotels)$/,
	page_name: "BookingConfirmation",
	page_category: "BookingConfirmation",
	eventCategory: "Overlay",
	eventLabel: "Verify Click",
	formName: "checkout",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
	eventAction: "Verification",
	currency: /^(GBP|EUR|USD)$/,
	funnel_name: /^(Trains|Packages|Hotels)$/,
	page_name: "BookingConfirmation",
	page_category: "BookingConfirmation",
	eventCategory: "Overlay",
	eventLabel: "Impressions",
	formName: "checkout",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},	
{
	eventAction: "Verification",
	currency: /^(GBP|EUR|USD)$/,
	funnel_name: /^(Trains|Packages|Hotels)$/,
	page_name: "BookingConfirmation",
	page_category: "BookingConfirmation",
	eventCategory: "Overlay",
	eventLabel: "Verify Success",
	formName: "checkout",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
	eventAction: "Register",
	currency: /^(GBP|EUR|USD)$/,
	funnel_name: /^(Trains|Packages|Hotels)$/,
	page_name: "BookingConfirmation",
	page_category: "BookingConfirmation",
	eventCategory: "Sign Up Now",
	eventLabel: "Register success",
	formName: "checkout",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
	eventCategory: "Exchange journey leg selection",
	eventAction: "Add",
	eventLabel: /^(Inbound|Outbound|Outbound\|Inbound)$/,
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
{
	eventCategory: "MYB interaction",
	eventAction: "Click",
	eventLabel: /^(Upgrade Booking|Exchange Booking|Get Tickets)$/,
	interactionSection: "action menu",
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
	{
	eventAction: "Enter A Booking Reference",
	eventCategory: "Bookings",
	eventLabel: /^(Search|Booking Added)$/,
	eventName: "InteractionEvent",
	event: "TealiumLink"
},
  {
    "event": "TealiumLink",
    "eventName": "InteractionEvent",
    "eventCategory": "Eurostar Chatbot",
    "eventAction": "Start Conversation",
    "conversationId": /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/
  },
{
	eventAction: "Click",
	eventCategory: "Lowest Fare Finder",
	eventLabel: /^(Select Destination|Select Outbound Month|Select Journey Type|Select Outbound Journey|Select Inbound Journey|Get Train Times)$/,
	currency: /^(GBP|EUR|USD)$/,
	sFromCode: /^\d{7}$/,
        sFromName: /.+/,
        sToCode: /^\d{7}$/,
        sToName: /.+/,
	sJourneyType: /(One way|Return)/,
	sPaxTotal: /\d+/,
        sPaxAdult: /\d+/,
        sPaxChildren: /\d+/,
        sPaxInfants: /\d+/,
        sPaxSenior: /\d+/,
        sPaxYouth: /\d+/,
        sPaxCompanion: /(\d+)?/,
	sDateOutboundBookingMonth: /^\d{4}_\S{3}$/,
	sDateInboundBookingMonth: /^\d{4}_\S{3}$/,
	sDateOutbound: /^null|\d{4}-\d{2}-\d{2}$/,
        sDateInbound: /^null|\d{4}-\d{2}-\d{2}$/,
	sOutboundLowestFare: /\d+/,
	sInboundLowestFare: /\d+/,
	priceAdultOutbound: /^(null|0|[1-9][0-9]{0,3}|10000)(\.[0-9]{1,2})?$/,
	priceAdultInbound: /^(null|0|[1-9][0-9]{0,3}|10000)(\.[0-9]{1,2})?$/,
	pointsOrRegular: /(regular booking|points booking)/,
	eventName: "InteractionEvent",
	event: "TealiumLink"
},	
];
